<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <OutputType>WinExe</OutputType>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <Nullable>enable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <ApplicationIcon>dxf-file.ico</ApplicationIcon>
	  <UseWPF>true</UseWPF>
	  <Platforms>AnyCPU;x64</Platforms>
	  <AssemblyName>Dxf Exporter</AssemblyName>
	  <Description>Программа для получения Dxf развёрток из файлов Inventor</Description>
	  <AssemblyVersion>1.0.2.0</AssemblyVersion>
	  <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="add-file.png" />
    <None Remove="binoculars.png" />
    <None Remove="dxf.png" />
    <None Remove="logo_ZV1.png" />
    <None Remove="Open-folder-add.png" />
    <None Remove="refresh settings.png" />
    <None Remove="refresh.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="add-file.png" />
    <Resource Include="binoculars.png" />
    <Resource Include="dxf-file.ico" />
    <Resource Include="dxf.png" />
    <Resource Include="logo_ZV1.png" />
    <Resource Include="Open-folder-add.png" />
    <Resource Include="refresh settings.png" />
    <Resource Include="refresh.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.4.2" />
    <PackageReference Include="netDxf" Version="2023.11.10" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.2" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Autodesk.Inventor.Interop">
      <HintPath>C:\Program Files\Autodesk\Inventor 2023\Bin\Public Assemblies\Autodesk.Inventor.Interop.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.Office.Interop.Outlook">
      <HintPath>C:\Program Files (x86)\Microsoft Visual Studio\Shared\Visual Studio Tools for Office\PIA\Office15\Microsoft.Office.Interop.Outlook.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
